### ISSUE TITLE
Spotify URI

### ISSUE THREAD

**Issue by bi0hazard1980uk** [mintopia/musicparty#21]
Cant get Spotify uri to work

Keep getting INVALID_CLIENT: Invalid redirect URI

Added the below to my .env

added the uri as directed as below.

#Create two new apps from spotify.
#You will need to set the redirect uri to ${PROTOCOL}${FQDN}/auth/spotify/search/redirect when you create them
SPOTIFY_CLIENT_ID=(Hidden)
SPOTIFY_CLIENT_SECRET=(Hidden)
SPOTIFY_SEARCH_CLIENT_ID=(Hidden)
SPOTIFY_SEARCH_CLIENT_SECRET=(Hidden)
SPOTIFY_SEARCH_REDIRECT_URI=${APP_URL}/auth/spotify/search/redirect
#UI required for this, available in debug output, will fall back to SPOTIFY_CLIENT_ID if not set
SPOTIFY_SEARCH_REFRESH_TOKEN=

**Comment by mintopia** [comment]
Hi, the readme will be incorrect at the moment as I've rewritten the develop branch of musicparty. I'll update the README this weekend. It's all much easier now.

**Comment by mintopia** [comment]
If you're using the develop branch (you should - it's much improved and better), as a quick summary - if you do the setup command so you can login, you can then go to settings and it'll tell you the URLs to use for it.

**Comment by bi0hazard1980uk** [comment]
Thanks for the updated instructions, I muddled my way through and got the site up and linked to Discord and Spotify, Now I am running into an issue where when I have linked to spotify I click the create party and I get an Error 500 Server error.

I had to change the .env as I am still working my way round Caddy so I am connecting via http rather than https. DUnno if this maybe the cause but any help would be appreciated.

services:
  nginx:
    image: ghcr.io/mintopia/musicparty-nginx:develop
    env_file: .env.nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - 80:80
    networks:
      - frontend
      - default
    volumes:
      - ./public:/var/www/storage/public

**Comment by mintopia** [comment]
Thanks for reporting this. There was an issue with the scopes we were requesting in Spotify authentication - we needed more scopes.

It now requests all the required ones for Party control and should now work.

Make sure your Spotify app has the the API and Web SDK options checked as well.

**Comment by mintopia** [comment]
Resolved - needed more scopes.
